[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = [
  "dotnet restore ./EnterpriseGradeInventoryAPI.csproj",
  "dotnet publish ./EnterpriseGradeInventoryAPI.csproj -c Release -o out"
]

[phases.start]
cmd = "dotnet out/EnterpriseGradeInventoryAPI.dll"

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:${PORT}"
